//! Hashes the bundled symbol-name wordlists into a NID -> name table at build
//! time, so a lookup is a binary search over a static array rather than a
//! hashmap built on every process start.
//!
//! Extra wordlists can be folded in without touching the crate by pointing
//! `SCE_NID_NAMES` at one or more newline-delimited files (`:`-separated).
//! Nothing under `names/` is third-party data — see `names/README.md`.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

include!("src/nid_hash.rs");

fn main() {
    println!("cargo:rerun-if-changed=src/nid_hash.rs");
    println!("cargo:rerun-if-changed=names");
    println!("cargo:rerun-if-env-changed=SCE_NID_NAMES");

    let mut paths: Vec<PathBuf> = Vec::new();
    let names_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("names");
    if let Ok(entries) = std::fs::read_dir(&names_dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.extension().is_some_and(|e| e == "txt") {
                paths.push(path);
            }
        }
    }
    paths.sort();

    if let Ok(extra) = std::env::var("SCE_NID_NAMES") {
        for path in extra.split(':').filter(|p| !p.is_empty()) {
            println!("cargo:rerun-if-changed={path}");
            paths.push(PathBuf::from(path));
        }
    }

    // BTreeMap keeps the output sorted by NID for the binary search, and
    // makes the generated file stable across builds.
    let mut table: BTreeMap<String, String> = BTreeMap::new();
    for path in &paths {
        let text = std::fs::read_to_string(path)
            .unwrap_or_else(|e| panic!("reading wordlist {}: {e}", path.display()));
        for line in text.lines() {
            let name = line.split('#').next().unwrap_or("").trim();
            if name.is_empty() {
                continue;
            }
            // First wordlist to claim a NID wins, so `names/` stays
            // predictable regardless of what SCE_NID_NAMES adds.
            table.entry(hash(name)).or_insert_with(|| name.to_owned());
        }
    }

    let mut out = String::new();
    out.push_str("/// NID -> name, sorted by NID. Generated by `build.rs`.\n");
    out.push_str(&format!(
        "pub static NID_NAMES: [(&str, &str); {}] = [\n",
        table.len()
    ));
    for (nid, name) in &table {
        out.push_str(&format!("    ({nid:?}, {name:?}),\n"));
    }
    out.push_str("];\n");

    let dest = Path::new(&std::env::var("OUT_DIR").unwrap()).join("nid_table.rs");
    std::fs::write(&dest, out).expect("writing nid_table.rs");
}
